apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: flask-sa
      containers:
      - name: backend
        image: CONTAINER_IMAGE
        ports:
        - containerPort: 5000
        env:
        - name: DB_SECRET_NAME
          value: "rds!cluster-6afe6fb6-5bfa-40a6-90b0-723302fba94c"
        - name: AWS_REGION
          value: "ap-northeast-3"
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_NAME
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "512Mi"